---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.16.0
      sourceRef:
        kind: HelmRepository
        name: vmware-charts
        namespace: flux-system
      interval: 5m
  values:
    annotations:
      reloader.stakater.com/auto: "true"
    configuration:
      provider: aws
      backupStorageLocation:
        # name: velero-aws
        bucket: velero-s3-dc2
        prefix: k8s
        config:
          region: us-east-2
      volumeSnapshotLocation:
        name: aws
        config:
          region: us-east-2
      resticTimeout: 6h
      default-volumes-to-restic: true
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.2.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    credentials:
      useSecret: true
      existingSecret: velero-aws-secret
    metrics:
      enabled: true
      # serviceMonitor:
      #   enabled: true
    # snapshotsEnabled: true
    snapshotsEnabled: false
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
    schedules:
      bi-daily-backup:
        schedule: "0 6,18 * * *"
        template:
          ttl: "168h"
