---
kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: backblaze-b2
  namespace: kasten-io
spec:
  locationSpec:
    type: ObjectStore
    objectStore:
      endpoint: s3.us-west-001.backblazeb2.com
      name: ${SECRET_B2_BUCKET}
      objectStoreType: S3
      pathType: Directory
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: secret
        name: k10-b2-secret
        namespace: kasten-io
  type: Location
