---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi-poller
      version: 7.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: golift/unifi-poller
      tag: 2.1.3
    env:
      TZ: "America/New_York"
      UP_UNIFI_DEFAULT_ROLE: "unifi-poller"
      UP_UNIFI_DEFAULT_URL: "${SECRET_UNIFI_POLLER_CONTROLLER_URL}"
      UP_UNIFI_DEFAULT_VERIFY_SSL: false
      UP_UNIFI_DEFAULT_USER: "${SECRET_UNIFI_POLLER_USERNAME}"
      UP_UNIFI_DEFAULT_PASS: "${SECRET_UNIFI_POLLER_PASSWORD}"
      UP_UNIFI_DEFAULT_SAVE_SITES: true
      UP_UNIFI_DEFAULT_SAVE_DPI: true
      UP_INFLUXDB_DISABLE: true
      UP_PROMETHEUS_DISABLE: false
      UP_PROMETHEUS_NAMESPACE: "unifipoller"
    prometheus:
      serviceMonitor:
        enabled: true
